#!/usr/bin/env bash
# Enforce the Conventional Commits style documented in README.md:
#   <type>(optional-scope): <summary>
# e.g. feat: add wind speed forecasting endpoint
set -euo pipefail

msg_file="$1"
subject="$(head -n1 "$msg_file")"

# Merge / revert commits generated by git are exempt.
case "$subject" in
  "Merge "*|"Revert "*)
    exit 0
    ;;
esac

pattern='^(feat|fix|chore|docs|spike|refactor|test|perf|build|ci|style)(\([a-z0-9_-]+\))?: .+'

if ! [[ "$subject" =~ $pattern ]]; then
  echo "error: commit message does not match the required convention." >&2
  echo "  expected: <type>(optional-scope): <summary>" >&2
  echo "  type      one of: feat, fix, chore, docs, spike, refactor, test, perf, build, ci, style" >&2
  echo "  example:  feat: add wind speed forecasting endpoint" >&2
  echo "got:        $subject" >&2
  echo "See README.md#branching--commits for details." >&2
  exit 1
fi
