-- =============================================================================
-- 60_docs / 01 — maintenance documents: stage, parse, chunk      STAGE: WOA_ADMIN
-- =============================================================================
-- Implements : US-27 (real files), US-28 (parsed with structure retained)
-- Proves     : T-37 (parsed output retains headings; a section is resolvable)
-- Authority  : ADR-0010 (parse, then search service), CMP-11
-- Parameter  : <% database %>
--
-- The corpus is generated by scripts/generate_maintenance_docs.py and uploaded
-- by `just deploy-docs` BEFORE this file's procedure runs. Every part number,
-- lead time and alarm code in it is copied from RAW, so a citation and the data
-- beside it cannot contradict each other.
--
-- ===================== WHY SECTION-LEVEL CHUNKS ==============================
--
-- A citation is only useful if a human can open it. So the unit of retrieval is
-- a SECTION, carrying its document id, title and heading: "VWS-MP-GBX-014 §4
-- Procedure" is resolvable; "chunk 17" is not. LAYOUT mode keeps the markdown
-- headings AI_PARSE_DOCUMENT extracts, and SPLIT_TEXT_MARKDOWN_HEADER cuts on
-- them, so the heading travels with its text rather than being reconstructed.
-- =============================================================================

use role WOA_ADMIN;
use database <% database %>;
use warehouse WOA_BUILD_WH;

-- Server-side encryption is required: AI_PARSE_DOCUMENT cannot read files on a
-- client-side-encrypted internal stage.
create stage if not exists DOCS.MAINTENANCE_DOCS
    directory = (enable = true)
    encryption = (type = 'SNOWFLAKE_SSE')
    comment = 'Synthetic maintenance procedures and policies (PDF). SYNTHETIC — fictional OEM.';

create table if not exists DOCS.DOC_PARSED (
    file_name     varchar(200)  not null,
    doc_id        varchar(40)   not null,
    parsed_md     varchar       not null,
    page_count    integer,
    parsed_at     timestamp_ntz not null,
    is_synthetic  boolean       not null default true,
    constraint pk_doc_parsed primary key (file_name)
);

create table if not exists DOCS.DOC_CHUNK (
    chunk_id      varchar(120)  not null,
    doc_id        varchar(40)   not null,
    doc_title     varchar(300),
    section       varchar(300),
    chunk_text    varchar       not null,
    file_name     varchar(200)  not null,
    is_synthetic  boolean       not null default true,
    constraint pk_doc_chunk primary key (chunk_id)
);

create or replace procedure DOCS.SP_PARSE_DOCUMENTS()
returns varchar
language sql
execute as caller
as
$$
declare
    n_files  integer;
    n_chunks integer;
begin
    alter stage DOCS.MAINTENANCE_DOCS refresh;

    delete from DOCS.DOC_PARSED;
    insert into DOCS.DOC_PARSED (file_name, doc_id, parsed_md, page_count, parsed_at)
    select
        relative_path,
        split_part(relative_path, '.', 1),
        p:content::varchar,
        p:metadata:pageCount::integer,
        current_timestamp()::timestamp_ntz
    from (
        select relative_path,
               ai_parse_document(to_file('@DOCS.MAINTENANCE_DOCS', relative_path), {'mode': 'LAYOUT'}) as p
        from directory(@DOCS.MAINTENANCE_DOCS)
        where relative_path ilike '%.pdf'
    );
    n_files := sqlrowcount;

    -- LAYOUT mode does not mark headings consistently: on this corpus it
    -- emitted '##' for six documents and plain lines for three identically
    -- styled ones (found by DQ-DOC-SECTIONS). We generate the corpus, so the
    -- heading shape is known — a numbered line with no trailing full stop, and
    -- a title line starting with the document id. Promote those where the
    -- parser did not. Already-marked lines start with '#' and do not match, so
    -- this is a no-op on the documents the parser got right.
    update DOCS.DOC_PARSED
    set parsed_md = regexp_replace(
            regexp_replace(parsed_md,
                '^(VWS-[A-Z]+-[A-Z]+-[0-9]{3} — [^\n]+)$', '# \\1', 1, 1, 'm'),
            '^([0-9]+\\. [A-Z][^\n]{0,80}[^.\n])$', '## \\1', 1, 0, 'm');

    -- The document title is the first-level heading LAYOUT mode emits for the
    -- PDF's title line; each section is a second-level heading beneath it.
    delete from DOCS.DOC_CHUNK;
    insert into DOCS.DOC_CHUNK (chunk_id, doc_id, doc_title, section, chunk_text, file_name)
    select
        d.doc_id || '#' || lpad(c.index::varchar, 2, '0'),
        d.doc_id,
        coalesce(c.value:headers:h1::varchar, d.doc_id),
        coalesce(c.value:headers:h2::varchar, 'Preamble'),
        c.value:chunk::varchar,
        d.file_name
    from DOCS.DOC_PARSED d,
         lateral flatten(input => snowflake.cortex.split_text_markdown_header(
             d.parsed_md,
             object_construct('#', 'h1', '##', 'h2'),
             2000, 200)) c
    where length(trim(c.value:chunk::varchar)) > 0;
    n_chunks := sqlrowcount;

    return n_files || ' documents parsed into ' || n_chunks || ' section chunks';
end;
$$;
